import { Platform, StyleSheet } from "react-native";

const FONT_REGULAR = "SourGummy";
const FONT_BOLD    = "SourGummy-Bold";

const COLORS = {
  background:         "#EAE7D6",
  primaryText:        "#4A5043",
  white:              "#FFFFFF",
  overlay:            "#F5F1E8",
  buttonBackground:   "#C4D7B2",
  dividerText:        "#8D8D8D",
  inputBackground:    "#D6DEAD",
  danger:             "#CC3333",
  shadow:             "#000",
  avatarBorder:       "#4A5043",
  usernameBackground: "#FFFFFF",
  separatorLine:      "#4A5043",
  modalOverlay:       "rgba(0,0,0,0.45)",
  modalBackground:    "#EAE7D6",
};

const SIZES = {
  paddingHorizontal:          24,
  headerHeight:               80,
  avatarSize:                 130,
  avatarBorderWidth:          2.5,
  avatarBorderRadius:         65,
  usernameFontSize:           18,
  labelFontSize:              16,
  buttonFontSize:             16,
  inputBorderRadius:          25,
  actionButtonBorderRadius:   30,
  actionButtonPaddingVertical: 16,
  separatorMarginVertical:    18,
  fieldMarginBottom:          14,
  modalBorderRadius:          20,
  modalPaddingHorizontal:     28,
  modalPaddingVertical:       30,
};

export { COLORS, SIZES };

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 15,
    backgroundColor: COLORS.background,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 10,
    zIndex: 2000,
  },
  menuOverlay: {
    position: "absolute",
    right: 0,
    width: "60%",
    backgroundColor: COLORS.overlay,
    paddingVertical: 20,
    paddingHorizontal: 10,
    borderBottomLeftRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: -4, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 20,
    zIndex: 1500,
  },
  menuBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1400,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 15,
  },
  menuItemIcon: {
    width: 28,
    height: 28,
    marginRight: 15,
    resizeMode: "contain",
  },
  menuItemText: {
    fontSize: 17,
    color: COLORS.primaryText,
    fontFamily: FONT_REGULAR,
  },
  headerIcon: {
    width: 48,
    height: 48,
  },

  content: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: SIZES.paddingHorizontal,
    paddingTop: 30,
  },

  avatarWrapper: {
    width: SIZES.avatarSize,
    height: SIZES.avatarSize,
    borderRadius: SIZES.avatarBorderRadius,
    borderWidth: SIZES.avatarBorderWidth,
    borderColor: COLORS.avatarBorder,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: COLORS.background,
  },
  avatarImage: {
    width: SIZES.avatarSize,
    height: SIZES.avatarSize,
    borderRadius: SIZES.avatarBorderRadius,
  },
  avatarEditOverlay: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "rgba(0,0,0,0.28)",
    alignItems: "center",
    paddingVertical: 5,
  },
  avatarEditText: {
    color: COLORS.white,
    fontSize: 11,
    fontWeight: "600",
    fontFamily: FONT_BOLD,
  },

  usernameTag: {
    marginTop: 14,
    backgroundColor: COLORS.usernameBackground,
    paddingHorizontal: 28,
    paddingVertical: 7,
    borderRadius: SIZES.inputBorderRadius,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  usernameText: {
    fontSize: SIZES.usernameFontSize,
    color: COLORS.primaryText,
    fontWeight: "500",
    fontFamily: FONT_REGULAR,
  },

  separator: {
    width: "100%",
    height: 1.2,
    backgroundColor: COLORS.separatorLine,
    opacity: 0.35,
    marginVertical: SIZES.separatorMarginVertical,
  },

  fieldRow: {
    width: "100%",
    backgroundColor: COLORS.inputBackground,
    borderRadius: SIZES.inputBorderRadius,
    paddingVertical: 16,
    paddingHorizontal: 22,
    marginBottom: SIZES.fieldMarginBottom,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fieldText: {
    fontSize: 17,
    color: COLORS.primaryText,
    flex: 1,
    fontWeight: "700",
    fontFamily: FONT_BOLD,
  },
  eyeButton: {
    paddingLeft: 10,
  },

  bottomButtons: {
    width: "100%",
    paddingHorizontal: SIZES.paddingHorizontal,
    paddingBottom: 36,
  },
  actionButton: {
    backgroundColor: COLORS.white,
    borderRadius: SIZES.actionButtonBorderRadius,
    paddingVertical: SIZES.actionButtonPaddingVertical,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.13,
    shadowRadius: 5,
    elevation: 5,
    gap: 10,
    marginBottom: 12,
  },
  actionButtonText: {
    fontSize: SIZES.buttonFontSize,
    color: COLORS.danger,
    fontWeight: "600",
    fontFamily: FONT_BOLD,
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: COLORS.modalOverlay,
    justifyContent: "center",
    alignItems: "center",
  },
  modalBox: {
    width: "85%",
    backgroundColor: COLORS.modalBackground,
    borderRadius: SIZES.modalBorderRadius,
    paddingHorizontal: SIZES.modalPaddingHorizontal,
    paddingVertical: SIZES.modalPaddingVertical,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: COLORS.primaryText,
    marginBottom: 14,
    textAlign: "center",
    fontFamily: FONT_BOLD,
  },
  modalInput: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: COLORS.primaryText,
    borderWidth: 1,
    borderColor: COLORS.inputBackground,
    marginBottom: 18,
    fontFamily: FONT_REGULAR,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  modalBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 20,
    alignItems: "center",
    backgroundColor: COLORS.buttonBackground,
  },
  modalBtnCancel: {
    backgroundColor: COLORS.inputBackground,
  },
  modalBtnText: {
    fontWeight: "700",
    fontSize: 14,
    color: COLORS.primaryText,
    fontFamily: FONT_BOLD,
  },

  warningTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.danger,
    marginBottom: 10,
    textAlign: "center",
    fontFamily: FONT_BOLD,
  },
  warningBody: {
    fontSize: 14,
    color: COLORS.primaryText,
    textAlign: "center",
    marginBottom: 22,
    lineHeight: 20,
    fontFamily: FONT_REGULAR,
  },
  warningConfirmBtn: {
    backgroundColor: COLORS.danger,
  },
  warningConfirmText: {
    color: COLORS.white,
    fontWeight: "700",
    fontSize: 14,
    fontFamily: FONT_BOLD,
  },
});